package com.sandip.dynamo_rest.entities;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.Getter;
import lombok.Setter;

@DynamoDBTable(tableName = "member")
@Getter
@Setter
public class Member {
    //    id, firstname, lastname, status
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private String firstname;

    @DynamoDBAttribute
    private String lastname;

    @DynamoDBAttribute
    @DynamoDBTypeConvertedEnum
    private MemberStatus status;
}
